services:
  lavagna:
    image: 324037305534.dkr.ecr.ap-south-1.amazonaws.com/ishay_lavagna_ecr:1.3  # Full ECR URL
    container_name: lavagna-app
    env_file:
      - .env
    # environment:
    #   # DB_DIALECT: MYSQL
    #   # # Update this with the RDS endpoint and port
    #   # DB_URL: jdbc:mysql://ishaylavagnadb.cdsmoa6q2ue9.ap-south-1.rds.amazonaws.com:3306/lavagna?autoReconnect=true&useSSL=false  # Use the RDS endpoint
    #   # DB_USERNAME: lavagna  # Your RDS username
    #   # DB_PASSWORD: lavagna  # Your RDS password
    #   # SPRING_PROFILE: dev
    networks:
      - lavagna-network
      - nginx-network

  nginx:
    image: nginx:1.19.10
    container_name: lavagna-nginx
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - /home/ubuntu/lavagna-deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/lavagna-deployment/src/main/webapp:/usr/share/nginx/html
      - /home/ubuntu/lavagna-deployment/target/lavagna/help:/usr/share/nginx/html/help
    networks:
      - nginx-network
      
  # mysql:
  #   image: mysql:5.7
  #   platform: linux/amd64
  #   container_name: lavagna-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root123
  #     MYSQL_DATABASE: lavagna
  #     MYSQL_USER: lavagna
  #     MYSQL_PASSWORD: lavagna
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - lavagna-mysql-data:/var/lib/mysql
  #   networks:
  #     - lavagna-network

networks:
  lavagna-network:
  nginx-network:
    driver: bridge
